name: result_pattern
description: This package provides a robust way of handling operations that may succeed or fail.
version: 1.0.0
repository: https://github.com/LeadcodeDev/result_pattern

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
